[project]
name = "heteromodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "brainspace>=0.1.20",
    "fbpca>=1.0",
    "h5py>=3.14.0",
    "joblib>=1.5.1",
    "matplotlib>=3.9.4",
    "neuromaps>=0.0.5",
    "nibabel>=5.3.2",
    "nsbtools",
    "numpy>=2.0.2",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "trimesh>=4.8.2",
]

[dependency-groups]
dev = [
    "imageio>=2.37.0",
    "ipykernel>=6.29.5",
    "memory-profiler>=0.61.0",
    "numba>=0.60.0",
    "numexpr>=2.10.2",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
nsbtools = { path = "../repos/nsbtools" }
